<?php		

// Establece como agrupar los estudios al mostrarlos en el frontend. Las siglas son los códigos de cada estudio,
// aquellos estudios que no son hallados en ningun grupo entran en la categoría de "Otros".
// Los estudios del grupo "Excluir" no son mostrados por ser irrelevantes o no ser realmente estudios.

$agrupar_estudios_array = array(
    'solicitud' => array(),
    'Hemograma' => array('HTO', 'HGB',  "CHCM", "HCM", "VCM", "RDW", 'LEU','NSEG', 'CAY',  'LIN', 'PLLA' ),
	'Funcion renal' => array('URE', 'CRE'),
    'Medio interno' => array('NAS', 'KAS', "MGS", 'CAS', "CL", "FOS", "CAI", "GLU"),
	'Hepatograma' => array('TGO', 'TGP', 'ALP', 'BIT', 'BID', 'BILI', "BITHEP", "BIDHEP", 'GGT'),
	'Coagulograma' => array('QUICKA', 'QUICKR', "APTT", "TTRO", "FIBRI"),
	'Gasometria' => array("PHT", "PO2T", "PCO2T", "CO3H", "EB", "SO2", "HB", "TM"),
	'Dosajes' => array("FK", "CS0R"),
	'Hierro' => array("FERR", "FES", "SATU", "TIB", "TRF"),
	'Lipidos' => array("COL", "HDLC", "LDLC","TRI"),
	'Excluir' => array('BAS', 'EOS', 'META', 'MI', 'MON', 'PRO', 'SB', 'SUMAL', "SR", "NE", "TEMP", "CTO2", "ERC", "QUICKT", "FIO2", "A/A", "RPLA", "ASP", "BILU", "COLOR", "CRIS", "EFQ", "USPRM", "SEDI", "UMUC", "COLCIT", "ASPCIT", "RTM", "MATD" ),
	'Otros' => array()
	);

// Array que asocia el código de un estudio con la abreviatura que será utilizada en la función "Copiar compacto"
$abreviar_nombres_estudios = array(
	"HTO" => "Hto",
	"HGB" => "Hb",
	"LEU" => "GB", 
	"PLLA" => "Plaq",
	"URE" => "Ur",
	"CRE" => "Cr",
	"NAS" => "Na",
	"KAS" => "K",
	"MGS" => "Mg",
	"CL" => "Cl",
	"CAS" => "Ca",
	"FOS" => "P",
	"CAI" => "CaI",
	"GLU" => "Glc",
	"TGO" => "GOT",
	"TGP" => "GPT",
	"ALP" => "FAL",
	"BIT" => "BT",
	"BID" => "BD",
	"GGT" => "GGT",
	"QUICKA" => "TP",
	"QUICKR" => "RIN",
	"APTT" => "APTT",
	"TTRO" => "TT",
	"FIBRI" => "Fibr",
	"PHT" => "PH",
	"PO2T" => "PO2",
	"PCO2T" => "PCO2",
	"CO3H" => "HCO3",
	"SO2" => "Sat O2",
	"FK" => "FK",
	"AMS" => "Amilasa",
	"LIS" => "Lipasa",
	"LDLC" => "LDL",
	"HDLC" => "HDL",
	"TRI" => "TG",
	"COL" => "COL",
	"BNP" => "BNP",
	"LAC" => "AL",
	"TROP" => "Tropo",
	"TSH" => "TSH", 
	"TT3" => "T3",
	"FT4" => "T4",
	"NAO" => "NaU",
	"KAO" => "KU",
	"ALB" => "Alb",
	"URU" => "Urea U",
	"CROE" => "CrU",
	"ERI" => "ERS",
	"PCR" => "PCR",
	"PCRU" => "PCR",
	"FERR" => "Ferritina",
	"FES" => "Ferremia",
	"SATU" => "Sat Transf",
	"TIB" => "TIBC",
	"TRF" => "Transf",
	"DMID" => "DD",
	"FIBRI" => "Fibr",
	"LDH" => "LDH"
	);
?> 